"""initial

Revision ID: dbe230ea1be9
Revises: 
Create Date: 2023-09-28 15:40:05.883239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe230ea1be9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='chat_id'),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('auto', sa.String(length=30), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    comment='Stores clients data'
    )
    op.create_index('idx_id_number', 'clients', ['id', 'number'], unique=False)
    op.create_table('masters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_name', sa.String(length=30), nullable=False),
    sa.Column('qualification', sa.String(length=15), server_default=sa.text("'gen'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('part_number', sa.String(length=15), nullable=True),
    sa.Column('original_number', sa.String(length=15), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('compatibility', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('norm_min', sa.Integer(), server_default=sa.text('60'), nullable=True),
    sa.Column('for_selection', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('requirements', sa.String(length=5), server_default=sa.text("'gen'"), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('credit_summ', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('order_summ', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('master_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=True),
    sa.Column('part_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_orders')
    op.drop_table('orders')
    op.drop_table('works')
    op.drop_table('statuses')
    op.drop_table('parts')
    op.drop_table('masters')
    op.drop_index('idx_id_number', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
