INSERT INTO public.statuses(
	id, status)
	VALUES (1, 'created'),
	(2,'created_push'),
	(3,'inwork'),
	(4, 'wait'),
	(5, 'ready'),
	(6, 'ready_push'),
	(7, 'canceled');

INSERT INTO public.masters(
	id, master_name, qualification)
	VALUES (1, 'Ivan', 'gen'),
	(2, 'Nikolay', 'el'),
	(3, 'Alexander', 'gen');

INSERT INTO public.works(
	id, work_name, price, norm_min, for_selection, requirements, description)
	VALUES (1, 'General Diagnostic', 250, 30, true, 'gen', 'Diagnostic gear, brakes, fluids, light, cooling'),
	(2, 'Computer diagnostic', 300, 30, true, 'el', 'Check errors, Engine, ABS, ESP'),
	(3, 'Brake system replace', 800, 120, true, 'gen', 'Replace brake disks, pads'),
	(4, 'TO (change oil, oli-filter)', 250, 60, true, 'gen', 'Change Oil, Oil-Filter');


ALTER TABLE TEST_TABLE ADD COLUMN ID BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL FIRST;